<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="libse">
      <HintPath>.\subtitleedit-src\src\libse\bin\Release\netstandard2.1\libse.dll</HintPath>
    </Reference>
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.4" />
  </ItemGroup>
</Project>
